### ISSUE TITLE
npm-home -> np 

### ISSUE THREAD

**Issue by charbelrami** [sindresorhus/npm-home#1]
It would be nice to include npm-home as the last step in [np](https://github.com/sindresorhus/np)
:)

**Comment by sindresorhus** [comment]
Why? I don't want to open the npm page every time I do a release.

**Comment by charbelrami** [comment]
Just to check that everything is good. It is not really useful to do this every time :sweat_smile:

**Comment by sindresorhus** [comment]
@charbelrami I would recommend you instead just do a shell alias for it:

``` sh
alias npf='np && npm-home'
```

Where the `f` in npf stands for `first`.

That way it only opens up on the first publish which is really when you'd want it.
