### ISSUE TITLE
Benefits vs. npm/shell built ins? 

### ISSUE THREAD

**Issue by ACollectionOfAtoms** [sindresorhus/npm-home#11]
Any benefit over: 
`npm repo <pkg>`
and
`open https://www.npmjs.com/package/<pkg>`
and
`open https://yarnpkg.com/en/package/<pkg>`
???

**Comment by sindresorhus** [comment]
> open https://www.npmjs.com/package/<pkg>

I don't want to manually type that each time. It also opens the current package if you run it without arguments. I could have done it with shell alias/function, but this is cross-platform and easier to maintain.
