### ISSUE TITLE
Accept multiple inputs

### ISSUE THREAD

**Issue by tommy-mitchell** [sindresorhus/npm-home#15]
Currently, `npm-home` only supports opening one URL at a time:

https://github.com/sindresorhus/npm-home/blob/9e1c49fac7224aeb91b6cd682039cfee38ee6a60/cli.js#L85-L86

It'd be nice if it could open multiple in one call:

```sh
> npm-home -g chalk meow ava
```

**Comment by sindresorhus** [comment]
👍
