### ISSUE TITLE
Consider generalizing the GitHub URL parsing to a new package

### ISSUE THREAD

**Issue by tommy-mitchell** [sindresorhus/npm-home#19]
I've found use for parsing a `package.json` to get a GitHub repo [separately](https://github.com/tommy-mitchell/npm-link-cli/blob/main/src/github.ts) and have another use case for it that would benefit from creating a separate package. I'd be happy to help add tests/documentation/types and update this package accordingly.

https://github.com/sindresorhus/npm-home/blob/40346cd007ca5c994122c7db357d9720efbefd4a/cli.js#L44-L84

### Possible API

```ts
// Just the fields we need
type PackageJson = {
  name: string;
  repository?: {
    url?: string;
  };
  homepage?: string;
};

declare async function githubUrlFromPackage(packageJson: PackageJson): {
  url?: string;
  warnings: string[];
}

export default githubUrlFromPackage;
```

Where the `warnings` are what are currently logged now:

```jsonc
[
  "The `repository` field in package.json should point to a Git repo and not a website. Please open an issue or pull request on `${name}`.",
  "The `repository` field in package.json is invalid. Please open an issue or pull request on `${name}`. Using the `homepage` field instead.",
  "No `homepage` field found in package.json." // A case I added
]
```

I don't think there's a need to throw errors. The user can supply the `package.json` data (whether fetched from NPM via `package-json` or manually, or read from a file, etc) and handle connection/missing package errors separately.

### Possible Names

- `gh-[url/repo]-from-pkg`

**Comment by sindresorhus** [comment]
Initial version: https://github.com/sindresorhus/repo-url-from-package

**Comment by sindresorhus** [comment]
Currently, it falls back to the homepage, should it do that?

1. Make it an option.
2. Make users do `githubRepoFromPackage(packageJson) ?? packageJson.homepage` if they want that.

I think I prefer the latter.

**Comment by tommy-mitchell** [comment]
Yeah, I prefer 2 as well. I think it makes sense for it to only return a value if it could find a GitHub URL.
