### ISSUE TITLE
Add implementation to let the user also open a package dependency page

### ISSUE THREAD

**Issue by vrunoa** [sindresorhus/npm-home#2]
hey @sindresorhus what do you think on this feature ? I add a param to the cli to let the users open also any of the (dev)dependencies that the package has. 
[https://github.com/Urucas/npm-home/blob/master/cli.js](https://github.com/Urucas/npm-home/blob/master/cli.js)
Let me know your opinion.

**Comment by sindresorhus** [comment]
Could be useful, but not something I would use, so I would recommend you instead publish it as a new module :)
