### ISSUE TITLE
`nh -g babel-preset-minify` crashes

### ISSUE THREAD

**Issue by lydell** [sindresorhus/npm-home#5]
```
❯ npm install npm-home
+ npm-home@1.4.1
added 78 packages in 2.241s

❯ ./node_modules/.bin/nh -g babel-preset-minify
Error: Expected a `target`
    at module.exports (/home/lydell/bugs/node_modules/opn/index.js:8:25)
    at packageJson.then.pkg (/home/lydell/bugs/node_modules/npm-home/cli.js:45:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Thanks for this very useful tool, btw!

**Comment by kevva** [comment]
Seems like [github-url-from-git](https://github.com/tj/node-github-url-from-git) fails to parse `https://github.com/babel/minify/tree/master/packages/babel-preset-minify`. Should we just fall back to using `pkg.repository.url` directly if `github-url-from-git` returns `undefined` @sindresorhus?

**Comment by sindresorhus** [comment]
That URL is an invalid `repository` URL though. So maybe better to throw and tell the user to open an issue on the repo to fix it?

**Comment by kevva** [comment]
I think it's because they are using the monorepo approach. Linking to the correct folder in the repo will result in that URL so I wouldn't say it's totally invalid.

**Comment by lydell** [comment]
Not sure if it helps you at all, but the github link in the sidebar to the right is correct here: https://www.npmjs.com/package/babel-preset-minify

**Comment by kevva** [comment]
It's because it points to the `homepage` field in `package.json`. It's pretty common to link to a landing page instead of the actual GitHub repo there so it's not guaranteed to work.

**Comment by lydell** [comment]
Well, if `homepage` seems to point to github perhaps you could use it as a fallback? ¯\\\_(ツ)\_/¯

**Comment by sindresorhus** [comment]
> Linking to the correct folder in the repo will result in that URL so I wouldn't say it's totally invalid.

Technically it's totally invalid as `repository` is supposed to be an URL to a repository, meaning something you can `git clone` directly.

**Comment by sindresorhus** [comment]
Here's what we'll do: If `github-url-from-git` returns `undefined`, we'll use `repository` if it's a normal URL (http/https). If not, we'll just use `homepage`. We also print a message about it being an invalid `repository` URL and such, but not throw.
