### ISSUE TITLE
Do something nicer when no argument is provided

### ISSUE THREAD

**Issue by lydell** [sindresorhus/npm-home#8]
```
❯ nh --version
1.5.0

❯ nh
TypeError: Cannot read property 'name' of undefined
    at readPkgUp.then.x (/home/lydell/.npm-global/lib/node_modules/npm-home/cli.js:70:34)
    at <anonymous>
```

**Comment by yeskunall** [comment]
![capture](https://user-images.githubusercontent.com/14703164/31745279-1336357c-b430-11e7-8b95-88ac87b064b2.JPG)

Works fine for me @lydell. What are you doing differently?

**Comment by lydell** [comment]
@yeskunall If you compare my comment and your screen shot, you can see that the versions differ. 1.6.0 has been released since I opened this issue, and it has fixed the problem.
